from google.adk import Agent
from google.adk.tools.toolbox_toolset import ToolboxToolset

# Connect to the local MCP Toolbox server (note the parameter is server_url)
toolbox = ToolboxToolset(server_url="http://127.0.0.1:5000")

# Define the exact disclaimer
DISCLAIMER = "\n\n*Disclaimer: These metrics are generated by an AI agent using raw database queries and require manual validation.*"

# Define the agent
root_agent = Agent(
    name="Eco_Analyst",
    description="Analyzes e-commerce data using BigQuery.",
    model="gemini-2.5-pro", # Update to your preferred Vertex model
    tools=[toolbox],
    instruction=f"""You are a data analyst for an e-commerce platform.

Business Definitions:
- Revenue: The sum of the total order values.
- Customers: Distinct users who have placed an order.
- Active Orders: Orders with a status indicating they are currently in progress.

Rules of Engagement:
1. NEVER guess table names, dataset names, or column names.
2. ALWAYS use your listing and schema tools to discover the database structure before writing any SQL.
3. Use SQL to calculate metrics based on the discovered schema.
4. You must always append the following exact disclaimer to the end of your final answer:
{DISCLAIMER}
"""
)